### ISSUE TITLE
 File "Generate.py", line 624, in <module>

### ISSUE THREAD

**Issue by rilyuuj** [FunctionClub/ZBench#12]
hi,

最后一步报错，我看了下之前的issue，报错似乎并不一样，是我Python版本太低了吗？
麻烦大佬看看

```
Traceback (most recent call last):
  File "Generate.py", line 624, in <module>
    shm = traceroute_to_dict("/tmp/shm.txt")
  File "Generate.py", line 29, in traceroute_to_dict
    res_data = urllib2.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1244, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>
cat: /tmp/gdu.txt_table: No such file or directory
curl: (6) Could not resolve host: api.zbench.kirito.moe; Unknown error
Result Address：https://zbench.kirito.moe/record.php?IKEY=
Your bench data is saved to /root/report.html

Do you want to check your Test Report? [y/n]:
```

**Comment by iamvicliu** [comment]
跟我一样

**Comment by rilyuuj** [comment]
> 跟我一样

凉了，没人维护。。
