### ISSUE TITLE
ZBench最后一项  失败

### ISSUE THREAD

**Issue by cusber** [FunctionClub/ZBench#2]
如题  
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/ZPing-CN.py", line 11, in <module>
    import argparse 
ImportError: No module named argparse
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "Generate.py", line 607, in <module>
    traceroute_to_table("/tmp/shm.txt")
  File "Generate.py", line 57, in traceroute_to_table
    string = string + template.format(i,x["ip"],x["route"],x["asn"],x["latency"]) + "\n"
ValueError: zero length field name in format

centos 6.8  x86_64    openvz

**Comment by baoang** [comment]
我的也有一些错误代码：

`Traceback (most recent call last):
  File "/usr/lib/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.6/SimpleHTTPServer.py", line 220, in <module>
    test()
  File "/usr/lib/python2.6/SimpleHTTPServer.py", line 216, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.6/BaseHTTPServer.py", line 588, in test
    httpd.serve_forever()
  File "/usr/lib/python2.6/SocketServer.py", line 234, in serve_forever
    r, w, e = _eintr_retry(select.select, [self], [], [], poll_interval)
  File "/usr/lib/python2.6/SocketServer.py", line 155, in _eintr_retry
    return func(*args)`

**Comment by KiritoMiao** [comment]
正在重构
