### ISSUE TITLE
ping的部分报错

### ISSUE THREAD

**Issue by soxvpshubs** [FunctionClub/ZBench#3]
```
Traceback (most recent call last):
  File "/tmp/ZPing.py", line 216, in <module>
    result = pinger.ping()
  File "/tmp/ZPing.py", line 196, in ping
    delay  =  self.ping_once()
  File "/tmp/ZPing.py", line 171, in ping_once
    icmp = socket.getprotobyname("icmp")
socket.error: protocol not found
```

**Comment by ghost** [comment]
谢谢提醒。
新版本已使用系统Ping工具来测试延迟
